### PR TITLE
Added size to index management plugin

### PR DESCRIPTION
**Pull request by minhtuev**
Updated the index management to keep track of size statistics

index-size

### CODE REVIEW

**Review by brimoor — CHANGES_REQUESTED** [review]
@minhtuev approach looks good so far here 👍 

Can you also add build status as we discussed offline so I can test them together?

**Comment by brimoor** [comment]
Side note: I haven't run the plugin locally yet, but based on the code, it looks like you figured out how to dynamically adjust `space` so that *if* there's a `Size` column, it won't wrap to the next line 💪

**Comment by minhtuev** [comment]
@brimoor done ✅

**Review by brimoor — APPROVED** [review]
LGTM, thanks for making this backwards-compatible with `fiftyone<0.25`! Very helpful since plugins aren't currently published as pip packages where the `version` can be dynamically handled by a package manager.

For future reference: make sure you [install the pre-commit hooks](https://github.com/voxel51/fiftyone-plugins/blob/main/CONTRIBUTING.md) when developing in this repo 😄

**Pull request merged**
